name: Build & Push API Image (Production)

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]
  workflow_dispatch:

env:
  REGISTRY: onlyusedtesla.azurecr.io
  IMAGE_NAME: out-api-v2
  SHA_TAG: ${{ github.sha }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ACR Login
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.PRODUCTION_REGISTRY_USERNAME }}
          password: ${{ secrets.PRODUCTION_REGISTRY_PASSWORD }}

      - name: Build
        run: |
          docker build \
            --build-arg BASE_IMAGE=${{ env.REGISTRY }}/base/node:20-alpine \
            --build-arg TAG=${{ env.SHA_TAG }} \
            -t $REGISTRY/$IMAGE_NAME:${{ env.SHA_TAG }} .

      - name: Push
        run: docker push $REGISTRY/$IMAGE_NAME:${{ env.SHA_TAG }}

      - name: Tag & Push latest
        if: github.ref == 'refs/heads/production'
        run: |
          docker tag  $REGISTRY/$IMAGE_NAME:${{ env.SHA_TAG }}  $REGISTRY/$IMAGE_NAME:latest
          docker push $REGISTRY/$IMAGE_NAME:latest

